package todd_and_steven;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class message {
  public static int NumberOfNodes() {
    return 1;
  }

  public static int MyNodeId() {
    return 0;
  }

  public static void PutChar(int target, char value) {
  }

  public static void PutInt(int target, int value) {
  }

  public static void PutLL(int target, long value) {
  }

  public static void Send(int target) {
  }

  public static int Receive(int source) {
    return 0;
  }

  public static char GetChar(int source) {
    return 0;
  }

  public static int GetInt(int source) {
    return 0;
  }

  public static long GetLL(int source) {
    return 0L;
  }

}
